set -eu

export BUILD_STATUS=0
export BUILDKITE_BUILD_NUMBER=12345
export BUILDKITE_BUILD_CHECKOUT_PATH="."
export BUILDKITE_PLUGIN_PRE_HOOK_COMMANDS_0="echo bob"
export BUILDKITE_PLUGIN_PRE_HOOK_COMMANDS_1="if [[ -z \"bob\" ]]; then"
export BUILDKITE_PLUGIN_PRE_HOOK_COMMANDS_2="    ENV=bob"
export BUILDKITE_PLUGIN_PRE_HOOK_COMMANDS_3="fi"
export BUILDKITE_PLUGIN_PRE_HOOK_COMMANDS_4="echo \"lookin good...\""
export BUILDKITE_PLUGIN_PRE_HOOK_COMMANDS_5="BUILD_STATUS=100"
export BUILDKITE_PLUGIN_PRE_HOOK_COMMANDS_6="export BUILD_STATUS"
export BUILDKITE_PLUGIN_PRE_HOOK_COMMANDS_7="echo \$BUILD_STATUS"

. hooks/pre-command

if [[ "$BUILD_STATUS" == "100" ]]; then
    echo "TESTS PASSED!"
    exit 0
else
    exit 1
fi
